#!/usr/bin/env ts-node
/**
 * Create an inbound proof on Cardano (simulates Storeman Group relay).
 *
 * This creates an Ed25519 signed proof at InboundMintCheck, spending a check
 * token and minting an inbound token at the handler address. The msg-agent
 * monitor will then detect it and process it (burn inbound token, mint bridge
 * tokens to the receiver).
 *
 * Prerequisites:
 *   - Yaci DevKit running (docker compose up -d)
 *   - Validators deployed (yarn deploy:local)
 *   - .env.local copied to .env
 *
 * Usage:
 *   cd msg-agent && npx ts-node ../qa/scripts/create-inbound-proof.ts
 *
 * Or with custom receiver/amount:
 *   RECEIVER=addr_test1q... AMOUNT=5000 npx ts-node ../qa/scripts/create-inbound-proof.ts
 */

import dotenv from 'dotenv';
import path from 'node:path';
dotenv.config({ path: path.join(__dirname, '../../msg-agent/.env') });

import { BlockfrostProvider, MeshWallet } from '@meshsdk/core';
import { createInboundTask } from '../../msg-agent/test/helpers/inbound';
import { deployAll, type DeploymentResult } from '../../msg-agent/test/helpers/deploy';
import { waitForTx, sleep } from '../../msg-agent/test/helpers/yaci';

const YACI_STORE_URL = process.env.BLOCKFROST_URL || 'http://localhost:8080/api/v1';
const SEED1 = process.env.ACCOUNT_SEED1;
const SEED3 = process.env.ACCOUNT_SEED3;

if (!SEED1 || !SEED3) {
    console.error('ACCOUNT_SEED1 and ACCOUNT_SEED3 must be set in .env');
    process.exit(1);
}

async function main() {
    const provider = new BlockfrostProvider(YACI_STORE_URL);

    // Create wallets
    const wallet1 = new MeshWallet({
        networkId: 0, fetcher: provider, submitter: provider,
        key: { type: 'cli', payment: '5820' + SEED1 },
    });
    await wallet1.init();

    const wallet3 = new MeshWallet({
        networkId: 0, fetcher: provider, submitter: provider,
        key: { type: 'cli', payment: '5820' + SEED3 },
    });
    await wallet3.init();

    const receiverAddr = process.env.RECEIVER
        || wallet3.addresses.baseAddressBech32
        || wallet3.addresses.enterpriseAddressBech32
        || '';
    const amount = parseInt(process.env.AMOUNT || '10000');

    // We need the deployment info. The deploy helper computes it from env vars + plutus.json.
    // But we can't re-deploy — we need to reconstruct the deployment result from the existing state.
    // The simplest approach: re-compute the validator addresses from the env vars.
    // This is what scripts.ts does internally.
    console.log('Reconstructing deployment info from .env...');

    // Import the scripts module which reads env vars
    const contractsInfo = (await import('../../msg-agent/src/scripts')).default;

    // Build a partial DeploymentResult from env vars + computed addresses
    const deployment: any = {
        checkTokenSymbol: process.env.CHECK_TOKEN_SYMBOL,
        checkTokenName: process.env.CHECK_TOKEN_NAME,
        inboundTokenPolicy: contractsInfo.inboundTokenPolicy,
        inboundMintCheckCbor: '', // We need to get this from the full computation
        inboundMintCheckAddress: '', // Same
        inboundMintCheckHash: '',
        inboundHandlerAddress: contractsInfo.inboundDemoAddress,
        inboundHandlerCbor: contractsInfo.inboundDemoScript.code,
        groupNftSymbol: process.env.GROUP_NFT_SYMBOL,
        groupNftName: process.env.GROUP_NFT_NAME,
        groupNftHolderAddress: process.env.GROUP_NFT_HOLDER,
        inboundTokenCbor: contractsInfo.inboundTokenScript.code,
        ed25519PrivKey: process.env.INBOUND_SIGNING_KEY || '',
    };

    // We need the InboundMintCheck address and the Ed25519 private key.
    // The private key is generated at deploy time and stored in .env.local.
    // Let's read it from .env
    if (!deployment.ed25519PrivKey) {
        console.error('INBOUND_SIGNING_KEY not set in .env');
        console.error('This was generated by deploy:local. Check your .env.local.');
        process.exit(1);
    }

    // Compute InboundMintCheck from env vars
    const { applyParamsToScript, resolveScriptHash, resolvePlutusScriptAddress } = await import('@meshsdk/core');
    const { mConStr0 } = await import('@meshsdk/common');
    const { defaultConfig } = await import('../../msg-agent/src/config');

    const groupNftInfo = mConStr0([deployment.groupNftSymbol, deployment.groupNftName]);
    const adminNftInfo = mConStr0([process.env.ADMIN_NFT_SYMBOL, process.env.ADMIN_NFT_NAME]);
    const checkTokenInfo = mConStr0([deployment.checkTokenSymbol, deployment.checkTokenName]);
    const gactParam = mConStr0([groupNftInfo, adminNftInfo, checkTokenInfo]);
    const inboundMintCheckParam = mConStr0([gactParam, deployment.inboundTokenPolicy]);
    const inboundMintCheckCbor = applyParamsToScript(
        defaultConfig.inboundMintCheck!.compiledCode, [inboundMintCheckParam],
    );
    deployment.inboundMintCheckCbor = inboundMintCheckCbor;
    deployment.inboundMintCheckHash = resolveScriptHash(inboundMintCheckCbor, defaultConfig.inboundMintCheck!.plutusVersion);
    deployment.inboundMintCheckAddress = resolvePlutusScriptAddress(
        { code: inboundMintCheckCbor, version: defaultConfig.inboundMintCheck!.plutusVersion }, 0,
    );

    console.log(`\nCreating inbound proof:`);
    console.log(`  Receiver: ${receiverAddr}`);
    console.log(`  Amount: ${amount}`);
    console.log(`  InboundMintCheck: ${deployment.inboundMintCheckAddress}`);
    console.log(`  InboundHandler: ${deployment.inboundHandlerAddress}`);

    const txHash = await createInboundTask({
        wallet: wallet1,
        provider,
        deployment,
        receiverAddress: receiverAddr,
        amount,
    });

    console.log(`\n✓ Inbound proof created: ${txHash}`);
    console.log(`\nThe msg-agent monitor should detect the inbound token at:`);
    console.log(`  ${deployment.inboundHandlerAddress}`);
    console.log(`\nAnd process it: burn inbound token → mint ${amount} bridge tokens to receiver.`);
}

main().catch(e => {
    console.error('Failed:', e.message || e);
    process.exit(1);
});
