#!/usr/bin/env ts-node
/**
 * deploy-and-generate-env.ts — Deploy validators on Yaci DevKit and generate .env.local
 *
 * This runs the full deployment pipeline (same as E2E test setup) and writes
 * a .env.local file with all the env vars the msg-agent needs to run.
 *
 * Prerequisites:
 *   docker compose up -d   (from repo root)
 *
 * Usage:
 *   cd msg-agent && npx ts-node scripts/deploy-and-generate-env.ts
 *   cp .env.local .env     # or: ln -sf .env.local .env
 *   yarn start             # run the monitor
 */

import {
    BlockfrostProvider, MeshWallet, deserializeAddress,
    applyParamsToScript, resolveScriptHash, resolvePlutusScriptAddress,
    PlutusScript,
} from '@meshsdk/core';
import { mConStr0 } from '@meshsdk/common';
import * as fs from 'fs';
import * as path from 'path';

// Import the E2E deploy helper (does the full deployment)
import { deployAll, type DeploymentResult } from '../test/helpers/deploy';
import { createDevnet, waitForYaci, topupAddress, sleep, YACI_STORE_URL } from '../test/helpers/yaci';
import { createWallet, ensureCollateral, walletAddress } from '../test/helpers/wallet';
import { defaultConfig } from '../src/config';

// Deterministic seeds for local testing
const SEED1 = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const SEED2 = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
const SEED3 = 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc';

async function main() {
    console.log('=== Deploy & Generate .env.local ===\n');

    // 1. Start devnet
    console.log('Setting up Yaci DevKit...');
    await createDevnet();
    await waitForYaci(120_000);

    // 2. Create and fund wallets
    const w1 = await createWallet(SEED1);
    const w2 = await createWallet(SEED2);
    const w3 = await createWallet(SEED3);

    console.log(`Wallet 1 (inbound worker):  ${w1.address}`);
    console.log(`Wallet 2 (outbound worker): ${w2.address}`);
    console.log(`Wallet 3 (user/client):     ${w3.address}`);

    await topupAddress(w1.address, 10_000);
    await topupAddress(w2.address, 10_000);
    await topupAddress(w3.address, 10_000);
    await sleep(5000);

    await ensureCollateral(w1.wallet);

    // 3. Deploy all validators
    console.log('\nDeploying validators...');
    const d = await deployAll(w1.wallet, w1.provider);

    // 4. Compute XPort params (need deployer PKH + nonce)
    const walletAddr = walletAddress(w1.wallet);
    const walletPkh = deserializeAddress(walletAddr).pubKeyHash;

    // 5. Compute the inbound handler script hash (needed for msg-agent's demoToken parameterization)
    const inboundHandlerScriptHash = resolveScriptHash(
        d.inboundHandlerCbor,
        defaultConfig.demoInbound!.plutusVersion,
    );

    // 6. Write .env.local
    const envContent = `# Generated by deploy-and-generate-env.ts
# Usage: cp .env.local .env && yarn start

# Provider — Yaci DevKit local
YACI_ADMIN_URL=http://localhost:10000
BLOCKFROST_URL=http://localhost:8080/api/v1

# Wallet seeds (deterministic for local testing)
ACCOUNT_SEED1=${SEED1}
ACCOUNT_SEED2=${SEED2}
ACCOUNT_SEED3=${SEED3}

# Network
NETWORK=0

# GroupNFTHolder address
GROUP_NFT_HOLDER=${d.groupNftHolderAddress}

# EVM contract address (used in CrossMsgData)
EVM_CONTRACT_ADDRESS=0xd6Ed4F1F50Cae0c5c7F514F3D0B1220c4a78F71d

# Receiver addresses for testing
RECEIVER_ON_ADA=${w3.address}
RECEIVER_ON_EVM=0x70997970C51812dc3A010C7d01b50e0d17dc79C8

# Transfer amount
CROSS_TRANSFER_AMOUNT=100

# Chain IDs
EVM_CHAIN_ID=2153201998
ADA_CHAIN_ID=2147485463

# --- Validator parameterization ---
# These are needed so scripts.ts computes the correct script addresses

# CheckToken (parameterizes InboundToken)
CHECK_TOKEN_SYMBOL=${d.checkTokenSymbol}
CHECK_TOKEN_NAME=${d.checkTokenName}

# GroupNFT (parameterizes OutboundToken)
GROUP_NFT_SYMBOL=${d.groupNftSymbol}
GROUP_NFT_NAME=${d.groupNftName}

# AdminNFT
ADMIN_NFT_SYMBOL=${d.adminNftSymbol}
ADMIN_NFT_NAME=${d.adminNftName}

# XPort (parameterizes xport script)
XPORT_PKH=${walletPkh}
XPORT_NONCE=0

# Ed25519 signing key for creating inbound proofs (test only — NOT the Storeman Group key)
INBOUND_SIGNING_KEY=${d.ed25519PrivKey}

# --- Deployment info (for reference) ---
# GroupNFT policy:        ${d.groupNftSymbol}
# AdminNFT policy:        ${d.adminNftSymbol}
# CheckToken policy:      ${d.checkTokenSymbol}
# InboundToken policy:    ${d.inboundTokenPolicy}
# OutboundToken policy:   ${d.outboundTokenPolicy}
# BridgeToken policy:     ${d.bridgeTokenPolicy}
# XPort hash:             ${d.xportHash}
# XPort address:          ${d.xportAddress}
# InboundMintCheck:       ${d.inboundMintCheckAddress}
# InboundHandler:         ${d.inboundHandlerAddress}
# OutboundHandler:        ${d.outboundHandlerAddress}
# GroupNFTHolder:         ${d.groupNftHolderAddress}
# Ed25519 pubkey (GPK):   ${d.ed25519PubKey}
# Ed25519 privkey:        ${d.ed25519PrivKey}
`;

    const envPath = path.join(__dirname, '..', '.env.local');
    fs.writeFileSync(envPath, envContent);
    console.log(`\n.env.local written to ${envPath}`);

    // Also write a .env.preprod template
    const preprodContent = `# Preprod testnet configuration
# Fill in BLOCKFROST_API_KEY and wallet seeds, then: cp .env.preprod .env

# Provider — Blockfrost Preprod
BLOCKFROST_API_KEY=<your-blockfrost-preprod-api-key>

# Wallet seeds (generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
ACCOUNT_SEED1=<seed1>
ACCOUNT_SEED2=<seed2>
ACCOUNT_SEED3=<seed3>

# Network
NETWORK=0

# GroupNFTHolder address (set after running deploy-prod-validators.ts)
GROUP_NFT_HOLDER=<addr_test1w...>

# EVM contract address
EVM_CONTRACT_ADDRESS=0xd6Ed4F1F50Cae0c5c7F514F3D0B1220c4a78F71d

# Receiver addresses
RECEIVER_ON_ADA=<cardano-preprod-address>
RECEIVER_ON_EVM=0x70997970C51812dc3A010C7d01b50e0d17dc79C8

# Transfer amount
CROSS_TRANSFER_AMOUNT=100

# Chain IDs
EVM_CHAIN_ID=2153201998
ADA_CHAIN_ID=2147485463

# --- Validator parameterization (set after deploy-prod-validators.ts) ---
CHECK_TOKEN_SYMBOL=<from-deploy-output>
CHECK_TOKEN_NAME=<from-deploy-output>
GROUP_NFT_SYMBOL=<from-deploy-output>
GROUP_NFT_NAME=<from-deploy-output>
ADMIN_NFT_SYMBOL=<from-deploy-output>
ADMIN_NFT_NAME=<from-deploy-output>
XPORT_PKH=<deployer-pubkey-hash>
XPORT_NONCE=0
`;

    const preprodPath = path.join(__dirname, '..', '.env.preprod');
    if (!fs.existsSync(preprodPath)) {
        fs.writeFileSync(preprodPath, preprodContent);
        console.log(`.env.preprod template written to ${preprodPath}`);
    }

    // 7. Verify the env works by computing addresses
    console.log('\n=== Verification ===');
    console.log('To use: cp .env.local .env && yarn start');
    console.log('\nThe monitor will watch:');
    console.log(`  Inbound tasks at:  ${d.inboundHandlerAddress}`);
    console.log(`  Outbound tasks at: ${d.outboundHandlerAddress}`);
    console.log(`  XPort output at:   ${d.xportAddress}`);
    console.log('\nTo create an inbound task (simulates Storeman relay):');
    console.log('  npx ts-node scripts/test-local.ts');
    console.log('\nTo create an outbound task (user sends bridge tokens):');
    console.log('  yarn client');
}

main().catch((e) => {
    console.error('Deploy failed:', e.message || e);
    process.exit(1);
});
